apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: An example of a basic Python application.
  annotations:
    github.com/project-slug: asadhanif3188/Python-App-with-ArgoCD
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental