replicaCount: 1
image:
  repository: asadhanif3188/python-with-argocd
  pullPolicy: IfNotPresent
  tag: "aa2b6f"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: python-app.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 3
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
