argo-cd:
  redis-ha:
    enabled: false

  controller:
    replicas: 1

  server:
    replicas: 1

  repoServer:
    replicas: 1

  applicationSet:
    replicas: 1

  # configs:
  #   params:
  #     server.insecure: true

  certificate:
    enabled: true

  global:
    domain: argocd.test.com

  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      ingressClassName: "nginx"
      tls: true