name: CICD
on: 
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    name: Build Docker Image and Push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # tags: asadhanif3188/python-with-argocd:${{ env.COMMIT_ID }}
          tags: asadhanif3188/python-with-argocd:${{ github.sha.substr(0, 6) }}

